config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#index'

  get 'destinations', to: 'destinations#index'
  get 'discover/jamaica', to: 'destinations#jamaica'
  get 'discover/cuba', to: 'destinations#cuba'
  get 'discover/brazil', to: 'destinations#brazil'

  resources :dinners

  get 'admin_dashboard', to: 'admin#dashboard'

  get 'menus', to: 'menus#index'
end

app/models/destination.rb
class Destination < ActiveRecord::Base
  has_many :dinners
end

app/models/dinner.rb
class Dinner < ActiveRecord::Base
  belongs_to :destination
  attachment :dinner_image
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def dashboard
    @dinners = Dinner.all
    @dinner = Dinner.new
    render layout: 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  def index
  end

  def jamaica
    @destination = Destination.where(name: params[:action].capitalize).first
    @dinners = @destination.dinners
    render layout: "jamaica"
  end

  def cuba
  end

  def brazil
  end

end

app/controllers/dinners_controller.rb
class DinnersController < ApplicationController
  before_action :set_dinner, only: [:show, :edit, :update, :destroy]

  # GET /dinners
  # GET /dinners.json
  def index
    @dinners = Dinner.all
  end

  # GET /dinners/1
  # GET /dinners/1.json
  def show
    @dinner = Dinner.find(params[:id])
  end

  # GET /dinners/new
  def new
    @dinner = Dinner.new
  end

  # GET /dinners/1/edit
  def edit
  end

  # POST /dinners
  # POST /dinners.json
  def create
    # binding.pry
    @dinner = Dinner.new(dinner_params)
    respond_to do |format|
      if @dinner.save
        format.html { redirect_to admin_dashboard_path }
        format.json { render :show, status: :created, location: @dinner }
      else
        format.html { render :new }
        format.json { render json: @dinner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dinners/1
  # PATCH/PUT /dinners/1.json
  def update
    respond_to do |format|
      if @dinner.update(dinner_params)
        format.html { redirect_to @dinner }
        format.json { render :show, status: :ok, location: @dinner }
      else
        format.html { render :edit }
        format.json { render json: @dinner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dinners/1
  # DELETE /dinners/1.json
  def destroy
    @dinner.destroy
    respond_to do |format|
      format.html { redirect_to dinners_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dinner
      @dinner = Dinner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dinner_params
      params.require(:dinner).permit(:name, :image, :dinner_image, :description, :price, :destination_id)
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

  def index
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def resolve_layout controller, location

    if controller == "destinations" && location == "jamaica"
      "<div class='st-content-#{location}'></>".html_safe
    elsif controller == "pages" && location == "index"
      "<div class='st-content-home'></>".html_safe
    else
      "<div class='st-content'></>".html_safe
    end
  end
end

app/helpers/dinners_helper.rb
module DinnersHelper
end

app/views/destinations/cuba.html.haml
%h1 Cuba

app/views/destinations/index.html.haml
%h1 Destination List

%p destinations

app/views/destinations/jamaica.html.haml
.destination-page
  =# image_tag('tropical_paradise.jpg', class: "page-destination-billboard")
  .destination-page-content
    .page-marquee
      %header.destination
        .codrops-links
        %h1.header-title
          %span.header-title__main Jamaica
          %span.header-title__part Out of Many, One People
          / %span.header-title__sub
      .intro
        %blockquote
          %em
            “Don't gain the world and lose your soul, wisdom is better than silver or gold...
            = succeed "" do
              %br/
          %span Bob Marley
    .container
      .text
        %section.js-section{"data-zoom-middle" => "2"}
          %h2
            %span.title-up Some cool title here
            %span.title-down The Adventure Begins
          %p.text-intro The Arawak and Taíno indigenous people, originating in South America, settled on the island between 4000 and 1000 BC. When Christopher Columbus arrived in 1494, there were more than 200 villages ruled by caciques (chiefs of villages). The south coast of Jamaica was the most populated, especially around the area now known as Old Harbour. The Taino still inhabited Jamaica when the English took control of the island in 1655. The Jamaican National Heritage Trust is attempting to locate and document any evidence of the Taino/Arawaks.
          .map-container
            .fader-top
            = image_tag('map.svg', class: 'map')

          %p.text-content We created some sort of sensation as we entered the capital of Iceland. The clocks were striking ten as we clattered down the long main street; it was a time when the populace were at leisure and on the street, and they evinced no little curiosity as we rode by them. They were congregated in small groups, and it was evident to us that we were being discussed—and no wonder, for we were a motley-looking cavalcade! We must have presented a very grotesque appearance, clad as we were in oilskins, and covered with mud from head to foot: it had been raining at intervals on the way, and we had had a rather disagreeable journey.
          %figure
            = image_tag "9.jpg", class: "js-image", 'data-pos' => "0.25"
            %figcaption All things come to an end, and so did our journey when we reached the end of the main street in Reykjavik
          %p.text-content Jamaica slowly gained increasing independence from the United Kingdom. In 1958, it became a province in the Federation of the West Indies, a federation among the British West Indies. Jamaica attained full independence by leaving the federation in 1962. Strong economic growth, averaging approximately 6% per annum, marked the first ten years of independence under conservative Jamaica Labour Party governments; they were led successively by Prime Ministers Alexander Bustamante, Donald Sangster and Hugh Shearer. The growth was fueled by strong private investments in bauxite/alumina, tourism, the manufacturing industry and, to a lesser extent, the agricultural sector.

          %p.text-content The optimism of the first decade was accompanied by a growing sense of inequality, and concern that the benefits of growth were not being shared by the urban poor. Combined with the effects of a slowdown in the global economy in 1970,the voters elected the PNP (People's National Party) in 1972. They tried to implement more socially equitable policies in education and health, but the economy suffered under their leadership. By 1980, Jamaica's gross national product had declined to some 25% below the 1972 level. Due to rising foreign and local debt, accompanied by large fiscal deficits, the government sought International Monetary Fund (IMF) financing from the United States and others. The international bankers imposed IMF austerity measures (with a greater than 25% interest rate per year).

          %p.text-content Economic deterioration continued into the mid-1980s, exacerbated by a number of factors; the first and third largest alumina producers, Alpart and Alcoa, closed, and there was a significant reduction in production by the second largest producer, Alcan. In addition, tourism decreased and Reynolds Jamaica Mines, Ltd. left the Jamaican industry. Independence, however widely celebrated in Jamaica, has in more recent years come into question. In 2011, a survey showed that approximately 60% of Jamaicans would push to once again become a British territory, citing years of social and fiscal mismanagement in the country.
        %section.js-section{"data-zoom-start" => "2"}
          %h2
            %span.title-up Some cool title herre
            %span.title-down A Helping Hand
          %p.text-content The optimism of the first decade was accompanied by a growing sense of inequality, and concern that the benefits of growth were not being shared by the urban poor. Combined with the effects of a slowdown in the global economy in 1970,the voters elected the PNP (People's National Party) in 1972. They tried to implement more socially equitable policies in education and health, but the economy suffered under their leadership. By 1980, Jamaica's gross national product had declined to some 25% below the 1972 level. Due to rising foreign and local debt, accompanied by large fiscal deficits, the government sought International Monetary Fund (IMF) financing from the United States and others. The international bankers imposed IMF austerity measures (with a greater than 25% interest rate per year).

          %p.text-content Economic deterioration continued into the mid-1980s, exacerbated by a number of factors; the first and third largest alumina producers, Alpart and Alcoa, closed, and there was a significant reduction in production by the second largest producer, Alcan. In addition, tourism decreased and Reynolds Jamaica Mines, Ltd. left the Jamaican industry. Independence, however widely celebrated in Jamaica, has in more recent years come into question. In 2011, a survey showed that approximately 60% of Jamaicans would push to once again become a British territory, citing years of social and fiscal mismanagement in the country.
          %figure
            = image_tag "5.jpg", class: "js-image", 'data-pos' => "0.6"
            %figcaption I was the geographer, whose mission it was to make a map of a small portion of the country traversed.
          %p.text-content The optimism of the first decade was accompanied by a growing sense of inequality, and concern that the benefits of growth were not being shared by the urban poor. Combined with the effects of a slowdown in the global economy in 1970,the voters elected the PNP (People's National Party) in 1972. They tried to implement more socially equitable policies in education and health, but the economy suffered under their leadership. By 1980, Jamaica's gross national product had declined to some 25% below the 1972 level. Due to rising foreign and local debt, accompanied by large fiscal deficits, the government sought International Monetary Fund (IMF) financing from the United States and others. The international bankers imposed IMF austerity measures (with a greater than 25% interest rate per year).

          %p.text-content Economic deterioration continued into the mid-1980s, exacerbated by a number of factors; the first and third largest alumina producers, Alpart and Alcoa, closed, and there was a significant reduction in production by the second largest producer, Alcan. In addition, tourism decreased and Reynolds Jamaica Mines, Ltd. left the Jamaican industry. Independence, however widely celebrated in Jamaica, has in more recent years come into question. In 2011, a survey showed that approximately 60% of Jamaicans would push to once again become a British territory, citing years of social and fiscal mismanagement in the country.
        %section.js-section{"data-stay" => "true", "data-zoom-start" => "2.5"}
          %h2
            %span.title-up Some coolre
            %span.title-down New Adventures
          %p.text-content The optimism of the first decade was accompanied by a growing sense of inequality, and concern that the benefits of growth were not being shared by the urban poor. Combined with the effects of a slowdown in the global economy in 1970,the voters elected the PNP (People's National Party) in 1972. They tried to implement more socially equitable policies in education and health, but the economy suffered under their leadership. By 1980, Jamaica's gross national product had declined to some 25% below the 1972 level. Due to rising foreign and local debt, accompanied by large fiscal deficits, the government sought International Monetary Fund (IMF) financing from the United States and others. The international bankers imposed IMF austerity measures (with a greater than 25% interest rate per year).

          %p.text-content Economic deterioration continued into the mid-1980s, exacerbated by a number of factors; the first and third largest alumina producers, Alpart and Alcoa, closed, and there was a significant reduction in production by the second largest producer, Alcan. In addition, tourism decreased and Reynolds Jamaica Mines, Ltd. left the Jamaican industry. Independence, however widely celebrated in Jamaica, has in more recent years come into question. In 2011, a survey showed that approximately 60% of Jamaicans would push to once again become a British territory, citing years of social and fiscal mismanagement in the country.
          %figure
            .js-gallery-content
              = image_tag("6.jpg")
              = image_tag("4.jpg")
              = image_tag("11.jpg")
              = image_tag("8.jpg")
            %figcaption An unexpected turn in our journey led us to many impressive places.
          %p.text-content The optimism of the first decade was accompanied by a growing sense of inequality, and concern that the benefits of growth were not being shared by the urban poor. Combined with the effects of a slowdown in the global economy in 1970,the voters elected the PNP (People's National Party) in 1972. They tried to implement more socially equitable policies in education and health, but the economy suffered under their leadership. By 1980, Jamaica's gross national product had declined to some 25% below the 1972 level. Due to rising foreign and local debt, accompanied by large fiscal deficits, the government sought International Monetary Fund (IMF) financing from the United States and others. The international bankers imposed IMF austerity measures (with a greater than 25% interest rate per year).

          %p.text-content Economic deterioration continued into the mid-1980s, exacerbated by a number of factors; the first and third largest alumina producers, Alpart and Alcoa, closed, and there was a significant reduction in production by the second largest producer, Alcan. In addition, tourism decreased and Reynolds Jamaica Mines, Ltd. left the Jamaican industry. Independence, however widely celebrated in Jamaica, has in more recent years come into question. In 2011, a survey showed that approximately 60% of Jamaicans would push to once again become a British territory, citing years of social and fiscal mismanagement in the country.

        %section.js-section{"data-stay" => "true", "data-zoom-start" => "0.8"}
    / /main

app/views/dinners/_form.html.haml
.new-dinner-form
  = form_for @dinner do |f|
    - if @dinner.errors.any?
      #error_explanation
        %h2= "#{pluralize(@dinner.errors.count, "error")} prohibited this dinner from being saved:"
        %ul
          - @dinner.errors.full_messages.each do |msg|
            %li= msg
    %div
      = f.label :name, "name"
      = f.text_field :name
    %div
      = f.label :dinner_image, "dinner image"
      = f.attachment_field :dinner_image, direct: true
    %div
      = f.label :description, "description"
      = f.text_area :description
    %div
      = f.label :price, "price"
      = f.number_field :price
    %div
      = f.label :destination_id, "destination"
      = f.number_field :destination_id

    .actions
      = f.submit 'Save'

app/views/dinners/_new.html.haml
.container
  = react_component("PanelName", { name: "Derrick" })
  %h1 New dinner

  = render 'dinners/form'

  = link_to 'Back', dinners_path

app/views/dinners/edit.html.haml
.inner-page-content
  .container
    %h1 Editing dinner

    = render 'form'

    = link_to 'Show', @dinner
    \|
    = link_to 'Back', dinners_path

app/views/dinners/index.html.haml
%h1 Listing dinners

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @dinners.each do |dinner|
      %tr
        %td= attachment_image_tag(dinner, :dinner_image, :fill, 70, 70, format: "jpg") unless @dinner_image_id.blank?
        %td= dinner.name
        %td= dinner.description
        %td= dinner.price

        %td= link_to 'Show', dinner
        %td= link_to 'Edit', edit_dinner_path(dinner)
        %td= link_to 'Destroy', dinner, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Dinner', new_dinner_path

app/views/dinners/show.html.haml
.inner-page-content
  %p#notice= notice
  .container
    = image_tag attachment_url(@dinner, :dinner_image, :fill, 300, 300, format: "jpg")

    %h1= @dinner.name
    %div= @dinner.description

    = link_to 'Edit', edit_dinner_path(@dinner)
    \|
    = link_to 'Back', dinners_path

app/views/layouts/admin.html.haml
= render partial: "shared/head"

%nav.navbar.navbar-fixed-top.admin-top
  %h1 Admin Panel
  = link_to "home", root_path
  \|
  = link_to "View Jamaica", discover_jamaica_path, class: "meal"
  \|
  = link_to "perform an action link", "#", class: "meal"
  \|
  = link_to "perform an action link", "#", class: "meal"

.container-fluid.admin

  .container.graphs
    .panel.action
      = image_tag('graph_placeholder1.png')
    .panel.action
      = image_tag('graph_placeholder2.png')

  .container.actions
    .panel.action
      - @dinners.each do |dinner|
        .dinner-thumbnail
          = image_tag attachment_url(dinner, :dinner_image, :fill, 170, 170, format: "jpg")
          %p
            = dinner.name
            =# dinner.description.truncate_words(4)
            = dinner.price
            .action_
            = link_to 'Show', dinner
            = link_to 'Edit', edit_dinner_path(dinner)
            = link_to 'Destroy', dinner, :method => :delete, :data => { :confirm => 'Are you sure?' }
      %br

    .panel.action
      = render partial: "dinners/new"
    .panel.action

app/views/layouts/application.html.haml
= render partial: "shared/head"

%body{:class => "data-controller-#{controller_name} data-action-#{action_name}"}
  #app-container.app-container
    = render partial: "shared/top_navigation"
    %p.notice
      = notice
    %p.alert
      = alert


    = render partial: "shared/side_navigation"
    .st-pusher
      .st-content
        .st-content-inner
          = yield
  .codrops-top.clearfix

app/views/layouts/jamaica.html.haml
= render partial: "shared/head"

%body{:class => "data-controller-#{controller_name} data-action-#{action_name}"}
  #app-container.app-container
    = render partial: "shared/top_navigation"
    = render partial: "shared/side_navigation"
    .st-pusher
      .st-content-jamaica
        .st-content-inner
          = yield
  .codrops-top.clearfix

app/views/menus/index.html.haml
.main
  %header.destination
    = image_tag('map.svg')
    .codrops-links
    %h1.header-title
      %span.header-title__main Jamaica
      %span.header-title__part A Caribbean Adventure
      %span.header-title__sub
        An interactive storytelling experiment with Canvas.
        = succeed "Photo" do
          %br/
        = succeed "." do
          %a{:href => "http://instagram.com/danrubin/"} Dan Rubin
  .intro
    %blockquote
      %em
        “Twenty years from now you will be more disappointed by the things you didn’t do
        = succeed "than" do
          %br/
      %span Mark Twain

app/views/pages/index.html.haml
= image_tag('cuba.jpg', class: "page-index-billboard")
.container.main
  .intro-index
    %blockquote
      %em
        discover authentically-prepared cultural cuisines
        delivered directly to your door.

  %h1.header-title
    %span.header-title__part-index No cooking or travel required

app/views/shared/_head.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Kula
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

app/views/shared/_side_navigation.html.haml
%nav.st-menu.nav-reveal
  %ul
    - if controller_name == 'destinations'
      - @dinners.each do |dinner|
        %li.meal-link
          = link_to dinner_path(dinner.id) do
            = image_tag attachment_url(dinner, :dinner_image, :fill, 150, 150, format: "jpg"), class: 'icon-location'
            %span.title-up.pull-right
              = dinner.name.titleize
    - else
      %li
        %a.icon.icon-destinations{:href => "#"} Destinations
      %ul.location-list
        %li.location-list-item
          = link_to "discover Jamaica".titleize, discover_jamaica_path, class: "icon icon-location jamaica"
        %li
          = link_to "discover Cuba".titleize, discover_cuba_path, class: "icon icon-location cuba"
        %li
          = link_to "discover Brazil".titleize, discover_brazil_path, class: "icon icon-location brazil"
      %li
        = link_to "about".titleize, root_path, class: "icon"
      %li
        = link_to "account".titleize, root_path, class: "icon"
    .menu-endcap

app/views/shared/_top_navigation.html.haml
%nav.navbar.navbar-fixed-top
  #icon_name
    %span#st-trigger-effects
      %button{"data-effect" => "nav-reveal", class: 'nav-hamburger' }
        .menu
        %i.fa.fa-bars.fa-4x
    %span.app_name KULA

app/views/shared/_top_navigation_layer.html.haml
.top-nav-stack
  #icon_name
    %span#st-trigger-effects
      %button{"data-effect" => "nav-reveal", class: 'nav-hamburger' }
        .menu menu
        %i.fa.fa-bars.fa-3x
    %span.app_name KULA